- name: installing catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disabled old nodejs and enabled nodejs:18
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  - name: installing nodejs
    ansible.builtin.yum:
      name: nodejs
      state: present
  - name: createing a user with name roboshop
    ansible.builtin.user:
      name: roboshop
  - name: createing a app directory
    ansible.builtin.file:
      path: /app 
      state: directory
  - name: downloading catalogue application using a link
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
  - name: un-ziping a package
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  - name: installing dependencys
    ansible.builtin.command: npm install
    args:
      chdir: /app
  - name: copying catalogue.service file
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  - name: doing demon-reload 
    ansible.builtin.systemd_service:
      daemon_reload: true
      state: restarted
      enabled: yes
  # - name: catalogue restart and enabled
  #   ansible.builtin.service:
  #     name: catalogue
  #     state: restarted
  #     enabled: yes
      




  

    