- name: installing catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disabled old nodejs and enabled nodejs:18
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  - name: installing nodejs
    ansible.builtin.yum:
      name: nodejs
      state: present
  - name: createing a user with name roboshop
    ansible.builtin.user:
      name: roboshop
  - name: createing a app directory
    ansible.builtin.file:
      path: /app 
      state: directory
  # - name: downloading a package using link
  #   ansible.builtin.get_link:
  #     url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
  #     dest: /tmp
  # - name: un-ziping a package
  #   ansible.builtin.unarchive:
  #     src: /tmp/catalogue.zip
  #     dest: /app
  #     remote_src: yes
  # - name: installing dependencys
  #   ansible.builtin.command: npm install
  #   args:
  #     chdir: /app

  

    