- name: installing catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disabled old nodejs and enabled nodejs:18
    ansible.builtin.command:
    - dnf module disable nodejs -y
    - dnf module enable nodejs:18 -y
  - name: installing nodejs
    ansible.builtin.yum:
      name: nodejs
      state: present
      