- name: installing dispatch componenets
  hosts: dispatch
  become: yes
  tasks:
  - name: Installing GoLang
    ansible.builtin.package:
      name: golang
      state: present
  - name: createing a user with name roboshop
    ansible.builtin.user:
      name: roboshop
  - name: createing a app directory
    ansible.builtin.file:
      path: /app 
      state: directory
  - name: downloading dispatch application using a link
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
      dest: /tmp
  - name: un-ziping a package
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: yes
  - name: installing dependencys
    ansible.builtin.command: "{{item}}"
    loop:
   # - go mod init dispatch
    - go get 
    - go build
    args:
      chdir: /app
    ignore_errors:
  - name: doing daemon-reload 
    ansible.builtin.systemd_service:
      daemon_reload: true
  - name: dispatch restart and enabled
    ansible.builtin.service:
      name: dispatch
      state: started
      enabled: yes
