- name: installing mysql components
  hosts: mysql
  become: yes
  tasks:
  - name: disable current version of mysql
    ansible.builtin.command: dnf module disable mysql -y
  
  - name: setup mysql.repo
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: Installing MySQL Server
    ansible.builtin.package:
      name: mysql-community-server
      state: present
      
  - name: start and enable MySQL Server
    ansible.builtin.service:
      state: started
      enabled: yes

  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
    

     